### PR TITLE
WidgetsBinding.instance! fixed

### PR DESCRIPTION
**Pull request by verzth**

### CODE REVIEW

**Comment by philqc** [comment]
@victorevox Could this be merged? It would be greatly appreciated, thanks!

**Comment by FreddyKaiser** [comment]
Any update on this ?

**Comment by atrope** [comment]
@victorevox ?

**Comment by fuku02** [comment]
Please merge!

**Comment by victorevox** [comment]
Merged! Thanks @verzth :) , Sorry for the late

**Pull request merged**
